### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by aman-plugenergy** [carlos-talavera/nextjs-laravel-breeze#2]
Great work on the repo. Was working on something similar but glad I found your repo. Saved me a lot of work.

Just a clarification. In the `UserResource.php` file you wrote:
```php
'emailVerifiedAt' => $this->email_verified_at,
// Use camelCase so it matches the property on the frontend
// (since login isn't a GET request, the TransformApiResponse middleware isn't applied)
```

Actually, the reason is not that the request to login is a POST request. The real reason is that the `TransformApiResponse` is added to the `api` middleware group and routes like `login` are in the `auth.php` file which is loaded via the `web.php` file which applies the `web` middleware group by default. So, the `api` middleware group will not be applied and hence, no `TransformApiResponse`.

Just wanted to clarify this so there is no confusion.

Again, great work ngl!

**Comment by carlos-talavera** [comment]
Hey, first of all, thank you! I'm glad you find it useful. Yeah, you're so right, I mixed up the behavior of `TransformApiRequest` with the one from `TransformApiResponse`, because in the latter there isn't even a validation for the HTTP method of the request. Thank you for the clarification, I will correct the comment so there's no confusion :)
